<?php

namespace Database\Seeders;

use App\Models\Data;
use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class DataSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        //
        // Data::create([
        //     'tanggal' => "24/12/25",
        //     'name' => "TERPAKAI",
        //     'stok_awal' => "2",
        //     'masuk' => "0",
        //     'keluar' => "0",
        //     'stok_akhir' => "2",
        //     'jumlah_stok_palet_baik' => "226",
        //     'jumlah_stok_palet_rusak' => "0",
        // ]);

        DB::table('datas')->insert(
            [
                // [
                //     'tanggal' => "20/11/01",
                //     'name' => "TERPAKAI",
                //     'stok_awal' => "100",
                //     'masuk' => "15",
                //     'keluar' => "0",
                //     'stok_akhir' => "115",
                //     'jumlah_stok_palet_baik' => "220",
                //     'jumlah_stok_palet_rusak' => "0",
                //     'created_at' => now(),
                //     'updated_at' => now(),
                // ],
                [
                    'tanggal' => "20/11/01",
                    'name' => "KOSONG",
                    'stok_awal' => "125",
                    'masuk' => "0",
                    'keluar' => "20",
                    'stok_akhir' => "105",
                    'jumlah_stok_palet_baik' => "220",
                    'jumlah_stok_palet_rusak' => "0",
                    'created_at' => now(),
                    'updated_at' => now(),
                ],
                // [
                //     'tanggal' => "20/11/02",
                //     'name' => "TERPAKAI",
                //     'stok_awal' => "115",
                //     'masuk' => "11",
                //     'keluar' => "0",
                //     'stok_akhir' => "126",
                //     'jumlah_stok_palet_baik' => "313",
                //     'jumlah_stok_palet_rusak' => "0",
                //     'created_at' => now(),
                //     'updated_at' => now(),
                // ],
                [
                    'tanggal' => "20/11/02",
                    'name' => "KOSONG",
                    'stok_awal' => "105",
                    'masuk' => "82",
                    'keluar' => "0",
                    'stok_akhir' => "187",
                    'jumlah_stok_palet_baik' => "313",
                    'jumlah_stok_palet_rusak' => "0",
                    'created_at' => now(),
                    'updated_at' => now(),
                ],
        //         [
        //             'tanggal' => "20/11/03",
        //             'name' => "TERPAKAI",
        //             'stok_awal' => "126",
        //             'masuk' => "0",
        //             'keluar' => "0",
        //             'stok_akhir' => "126",
        //             'jumlah_stok_palet_baik' => "313",
        //             'jumlah_stok_palet_rusak' => "0",
        //             'created_at' => now(),
        //             'updated_at' => now(),
        //         ],
        //         [
        //             'tanggal' => "20/11/03",
        //             'name' => "KOSONG",
        //             'stok_awal' => "187",
        //             'masuk' => "0",
        //             'keluar' => "0",
        //             'stok_akhir' => "187",
        //             'jumlah_stok_palet_baik' => "313",
        //             'jumlah_stok_palet_rusak' => "0",
        //             'created_at' => now(),
        //             'updated_at' => now(),
        //         ],
        //         [
        //             'tanggal' => "20/11/04",
        //             'name' => "TERPAKAI",
        //             'stok_awal' => "126",
        //             'masuk' => "0",
        //             'keluar' => "8",
        //             'stok_akhir' => "118",
        //             'jumlah_stok_palet_baik' => "438",
        //             'jumlah_stok_palet_rusak' => "0",
        //             'created_at' => now(),
        //             'updated_at' => now(),
        //         ],
        //         [
        //             'tanggal' => "20/11/04",
        //             'name' => "KOSONG",
        //             'stok_awal' => "187",
        //             'masuk' => "133",
        //             'keluar' => "0",
        //             'stok_akhir' => "320",
        //             'jumlah_stok_palet_baik' => "438",
        //             'jumlah_stok_palet_rusak' => "0",
        //             'created_at' => now(),
        //             'updated_at' => now(),
        //         ],
        //         [
        //             'tanggal' => "20/11/05",
        //             'name' => "TERPAKAI",
        //             'stok_awal' => "118",
        //             'masuk' => "0",
        //             'keluar' => "0",
        //             'stok_akhir' => "118",
        //             'jumlah_stok_palet_baik' => "438",
        //             'jumlah_stok_palet_rusak' => "0",
        //             'created_at' => now(),
        //             'updated_at' => now(),
        //         ],
        //         [
        //             'tanggal' => "20/11/05",
        //             'name' => "KOSONG",
        //             'stok_awal' => "320",
        //             'masuk' => "0",
        //             'keluar' => "0",
        //             'stok_akhir' => "320",
        //             'jumlah_stok_palet_baik' => "438",
        //             'jumlah_stok_palet_rusak' => "0",
        //             'created_at' => now(),
        //             'updated_at' => now(),
        //         ],
        //         [
        //             'tanggal' => "20/11/06",
        //             'name' => "TERPAKAI",
        //             'stok_awal' => "118",
        //             'masuk' => "0",
        //             'keluar' => "0",
        //             'stok_akhir' => "118",
        //             'jumlah_stok_palet_baik' => "438",
        //             'jumlah_stok_palet_rusak' => "0",
        //             'created_at' => now(),
        //             'updated_at' => now(),
        //         ],
        //         [
        //             'tanggal' => "20/11/06",
        //             'name' => "KOSONG",
        //             'stok_awal' => "320",
        //             'masuk' => "0",
        //             'keluar' => "0",
        //             'stok_akhir' => "320",
        //             'jumlah_stok_palet_baik' => "438",
        //             'jumlah_stok_palet_rusak' => "0",
        //             'created_at' => now(),
        //             'updated_at' => now(),
        //         ],
        //         [
        //             'tanggal' => "20/11/07",
        //             'name' => "TERPAKAI",
        //             'stok_awal' => "118",
        //             'masuk' => "0",
        //             'keluar' => "75",
        //             'stok_akhir' => "43",
        //             'jumlah_stok_palet_baik' => "298",
        //             'jumlah_stok_palet_rusak' => "0",
        //             'created_at' => now(),
        //             'updated_at' => now(),
        //         ],
        //         [
        //             'tanggal' => "20/11/07",
        //             'name' => "KOSONG",
        //             'stok_awal' => "320",
        //             'masuk' => "0",
        //             'keluar' => "65",
        //             'stok_akhir' => "255",
        //             'jumlah_stok_palet_baik' => "298",
        //             'jumlah_stok_palet_rusak' => "0",
        //             'created_at' => now(),
        //             'updated_at' => now(),
        //         ],
        //         [
        //             'tanggal' => "20/11/08",
        //             'name' => "TERPAKAI",
        //             'stok_awal' => "43",
        //             'masuk' => "26",
        //             'keluar' => "0",
        //             'stok_akhir' => "69",
        //             'jumlah_stok_palet_baik' => "323",
        //             'jumlah_stok_palet_rusak' => "0",
        //             'created_at' => now(),
        //             'updated_at' => now(),
        //         ],
        //         [
        //             'tanggal' => "20/11/08",
        //             'name' => "KOSONG",
        //             'stok_awal' => "255",
        //             'masuk' => "0",
        //             'keluar' => "1",
        //             'stok_akhir' => "254",
        //             'jumlah_stok_palet_baik' => "323",
        //             'jumlah_stok_palet_rusak' => "0",
        //             'created_at' => now(),
        //             'updated_at' => now(),
        //         ],
        //         [
        //             'tanggal' => "20/11/09",
        //             'name' => "TERPAKAI",
        //             'stok_awal' => "69",
        //             'masuk' => "14",
        //             'keluar' => "0",
        //             'stok_akhir' => "83",
        //             'jumlah_stok_palet_baik' => "302",
        //             'jumlah_stok_palet_rusak' => "0",
        //             'created_at' => now(),
        //             'updated_at' => now(),
        //         ],
        //         [
        //             'tanggal' => "20/11/09",
        //             'name' => "KOSONG",
        //             'stok_awal' => "254",
        //             'masuk' => "5",
        //             'keluar' => "40",
        //             'stok_akhir' => "219",
        //             'jumlah_stok_palet_baik' => "302",
        //             'jumlah_stok_palet_rusak' => "0",
        //             'created_at' => now(),
        //             'updated_at' => now(),
        //         ],
        //         [
        //             'tanggal' => "20/11/10",
        //             'name' => "TERPAKAI",
        //             'stok_awal' => "83",
        //             'masuk' => "18",
        //             'keluar' => "0",
        //             'stok_akhir' => "101",
        //             'jumlah_stok_palet_baik' => "324",
        //             'jumlah_stok_palet_rusak' => "0",
        //             'created_at' => now(),
        //             'updated_at' => now(),
        //         ],
        //         [
        //             'tanggal' => "20/11/10",
        //             'name' => "KOSONG",
        //             'stok_awal' => "219",
        //             'masuk' => "4",
        //             'keluar' => "0",
        //             'stok_akhir' => "223",
        //             'jumlah_stok_palet_baik' => "324",
        //             'jumlah_stok_palet_rusak' => "0",
        //             'created_at' => now(),
        //             'updated_at' => now(),
        //         ],
        //         [
        //             'tanggal' => "20/11/11",
        //             'name' => "TERPAKAI",
        //             'stok_awal' => "101",
        //             'masuk' => "13",
        //             'keluar' => "0",
        //             'stok_akhir' => "114",
        //             'jumlah_stok_palet_baik' => "340",
        //             'jumlah_stok_palet_rusak' => "0",
        //             'created_at' => now(),
        //             'updated_at' => now(),
        //         ],
        //         [
        //             'tanggal' => "20/11/11",
        //             'name' => "KOSONG",
        //             'stok_awal' => "223",
        //             'masuk' => "3",
        //             'keluar' => "0",
        //             'stok_akhir' => "226",
        //             'jumlah_stok_palet_baik' => "340",
        //             'jumlah_stok_palet_rusak' => "0",
        //             'created_at' => now(),
        //             'updated_at' => now(),
        //         ],
        //         [
        //             'tanggal' => "20/11/12",
        //             'name' => "TERPAKAI",
        //             'stok_awal' => "114",
        //             'masuk' => "0",
        //             'keluar' => "0",
        //             'stok_akhir' => "114",
        //             'jumlah_stok_palet_baik' => "340",
        //             'jumlah_stok_palet_rusak' => "0",
        //             'created_at' => now(),
        //             'updated_at' => now(),
        //         ],
        //         [
        //             'tanggal' => "20/11/12",
        //             'name' => "KOSONG",
        //             'stok_awal' => "226",
        //             'masuk' => "0",
        //             'keluar' => "0",
        //             'stok_akhir' => "226",
        //             'jumlah_stok_palet_baik' => "340",
        //             'jumlah_stok_palet_rusak' => "0",
        //             'created_at' => now(),
        //             'updated_at' => now(),
        //         ],
        //         [
        //             'tanggal' => "20/11/13",
        //             'name' => "TERPAKAI",
        //             'stok_awal' => "114",
        //             'masuk' => "6",
        //             'keluar' => "0",
        //             'stok_akhir' => "120",
        //             'jumlah_stok_palet_baik' => "454",
        //             'jumlah_stok_palet_rusak' => "0",
        //             'created_at' => now(),
        //             'updated_at' => now(),
        //         ],
        //         [
        //             'tanggal' => "20/11/13",
        //             'name' => "KOSONG",
        //             'stok_awal' => "226",
        //             'masuk' => "128",
        //             'keluar' => "20",
        //             'stok_akhir' => "334",
        //             'jumlah_stok_palet_baik' => "454",
        //             'jumlah_stok_palet_rusak' => "0",
        //             'created_at' => now(),
        //             'updated_at' => now(),
        //         ],
        //         [
        //             'tanggal' => "20/11/14",
        //             'name' => "TERPAKAI",
        //             'stok_awal' => "120",
        //             'masuk' => "18",
        //             'keluar' => "0",
        //             'stok_akhir' => "138",
        //             'jumlah_stok_palet_baik' => "457",
        //             'jumlah_stok_palet_rusak' => "0",
        //             'created_at' => now(),
        //             'updated_at' => now(),
        //         ],
        //         [
        //             'tanggal' => "20/11/14",
        //             'name' => "KOSONG",
        //             'stok_awal' => "334",
        //             'masuk' => "5",
        //             'keluar' => "20",
        //             'stok_akhir' => "319",
        //             'jumlah_stok_palet_baik' => "457",
        //             'jumlah_stok_palet_rusak' => "0",
        //             'created_at' => now(),
        //             'updated_at' => now(),
        //         ],
        //         [
        //             'tanggal' => "20/11/15",
        //             'name' => "TERPAKAI",
        //             'stok_awal' => "138",
        //             'masuk' => "2",
        //             'keluar' => "0",
        //             'stok_akhir' => "140",
        //             'jumlah_stok_palet_baik' => "459",
        //             'jumlah_stok_palet_rusak' => "0",
        //             'created_at' => now(),
        //             'updated_at' => now(),
        //         ],
        //         [
        //             'tanggal' => "20/11/15",
        //             'name' => "KOSONG",
        //             'stok_awal' => "319",
        //             'masuk' => "0",
        //             'keluar' => "0",
        //             'stok_akhir' => "319",
        //             'jumlah_stok_palet_baik' => "459",
        //             'jumlah_stok_palet_rusak' => "0",
        //             'created_at' => now(),
        //             'updated_at' => now(),
        //         ],
        //         [
        //             'tanggal' => "20/11/16",
        //             'name' => "TERPAKAI",
        //             'stok_awal' => "140",
        //             'masuk' => "0",
        //             'keluar' => "0",
        //             'stok_akhir' => "140",
        //             'jumlah_stok_palet_baik' => "459",
        //             'jumlah_stok_palet_rusak' => "0",
        //             'created_at' => now(),
        //             'updated_at' => now(),
        //         ],
        //         [
        //             'tanggal' => "20/11/16",
        //             'name' => "KOSONG",
        //             'stok_awal' => "319",
        //             'masuk' => "0",
        //             'keluar' => "0",
        //             'stok_akhir' => "319",
        //             'jumlah_stok_palet_baik' => "459",
        //             'jumlah_stok_palet_rusak' => "0",
        //             'created_at' => now(),
        //             'updated_at' => now(),
        //         ],
        //         [
        //             'tanggal' => "20/11/17",
        //             'name' => "TERPAKAI",
        //             'stok_awal' => "140",
        //             'masuk' => "5",
        //             'keluar' => "0",
        //             'stok_akhir' => "145",
        //             'jumlah_stok_palet_baik' => "466",
        //             'jumlah_stok_palet_rusak' => "0",
        //             'created_at' => now(),
        //             'updated_at' => now(),
        //         ],
        //         [
        //             'tanggal' => "20/11/17",
        //             'name' => "KOSONG",
        //             'stok_awal' => "319",
        //             'masuk' => "2",
        //             'keluar' => "0",
        //             'stok_akhir' => "321",
        //             'jumlah_stok_palet_baik' => "466",
        //             'jumlah_stok_palet_rusak' => "0",
        //             'created_at' => now(),
        //             'updated_at' => now(),
        //         ],
        //         [
        //             'tanggal' => "20/11/18",
        //             'name' => "TERPAKAI",
        //             'stok_awal' => "145",
        //             'masuk' => "8",
        //             'keluar' => "16",
        //             'stok_akhir' => "137",
        //             'jumlah_stok_palet_baik' => "457",
        //             'jumlah_stok_palet_rusak' => "0",
        //             'created_at' => now(),
        //             'updated_at' => now(),
        //         ],
        //         [
        //             'tanggal' => "20/11/18",
        //             'name' => "KOSONG",
        //             'stok_awal' => "321",
        //             'masuk' => "3",
        //             'keluar' => "4",
        //             'stok_akhir' => "320",
        //             'jumlah_stok_palet_baik' => "457",
        //             'jumlah_stok_palet_rusak' => "0",
        //             'created_at' => now(),
        //             'updated_at' => now(),
        //         ],
        //         [
        //             'tanggal' => "20/11/19",
        //             'name' => "TERPAKAI",
        //             'stok_awal' => "137",
        //             'masuk' => "0",
        //             'keluar' => "64",
        //             'stok_akhir' => "73",
        //             'jumlah_stok_palet_baik' => "377",
        //             'jumlah_stok_palet_rusak' => "0",
        //             'created_at' => now(),
        //             'updated_at' => now(),
        //         ],
        //         [
        //             'tanggal' => "20/11/19",
        //             'name' => "KOSONG",
        //             'stok_awal' => "320",
        //             'masuk' => "0",
        //             'keluar' => "16",
        //             'stok_akhir' => "304",
        //             'jumlah_stok_palet_baik' => "377",
        //             'jumlah_stok_palet_rusak' => "0",
        //             'created_at' => now(),
        //             'updated_at' => now(),
        //         ],
        //         [
        //             'tanggal' => "20/11/20",
        //             'name' => "TERPAKAI",
        //             'stok_awal' => "73",
        //             'masuk' => "0",
        //             'keluar' => "6",
        //             'stok_akhir' => "67",
        //             'jumlah_stok_palet_baik' => "373",
        //             'jumlah_stok_palet_rusak' => "0",
        //             'created_at' => now(),
        //             'updated_at' => now(),
        //         ],
        //         [
        //             'tanggal' => "20/11/20",
        //             'name' => "KOSONG",
        //             'stok_awal' => "304",
        //             'masuk' => "2",
        //             'keluar' => "0",
        //             'stok_akhir' => "306",
        //             'jumlah_stok_palet_baik' => "373",
        //             'jumlah_stok_palet_rusak' => "0",
        //             'created_at' => now(),
        //             'updated_at' => now(),
        //         ],
        //         [
        //             'tanggal' => "20/11/21",
        //             'name' => "TERPAKAI",
        //             'stok_awal' => "67",
        //             'masuk' => "0",
        //             'keluar' => "0",
        //             'stok_akhir' => "67",
        //             'jumlah_stok_palet_baik' => "373",
        //             'jumlah_stok_palet_rusak' => "0",
        //             'created_at' => now(),
        //             'updated_at' => now(),
        //         ],
        //         [
        //             'tanggal' => "20/11/21",
        //             'name' => "KOSONG",
        //             'stok_awal' => "306",
        //             'masuk' => "0",
        //             'keluar' => "0",
        //             'stok_akhir' => "306",
        //             'jumlah_stok_palet_baik' => "373",
        //             'jumlah_stok_palet_rusak' => "0",
        //             'created_at' => now(),
        //             'updated_at' => now(),
        //         ],
        //         [
        //             'tanggal' => "20/11/22",
        //             'name' => "TERPAKAI",
        //             'stok_awal' => "67",
        //             'masuk' => "0",
        //             'keluar' => "0",
        //             'stok_akhir' => "67",
        //             'jumlah_stok_palet_baik' => "373",
        //             'jumlah_stok_palet_rusak' => "0",
        //             'created_at' => now(),
        //             'updated_at' => now(),
        //         ],
        //         [
        //             'tanggal' => "20/11/22",
        //             'name' => "KOSONG",
        //             'stok_awal' => "306",
        //             'masuk' => "0",
        //             'keluar' => "0",
        //             'stok_akhir' => "306",
        //             'jumlah_stok_palet_baik' => "373",
        //             'jumlah_stok_palet_rusak' => "0",
        //             'created_at' => now(),
        //             'updated_at' => now(),
        //         ],
        //         [
        //             'tanggal' => "20/11/23",
        //             'name' => "TERPAKAI",
        //             'stok_awal' => "67",
        //             'masuk' => "0",
        //             'keluar' => "0",
        //             'stok_akhir' => "67",
        //             'jumlah_stok_palet_baik' => "373",
        //             'jumlah_stok_palet_rusak' => "0",
        //             'created_at' => now(),
        //             'updated_at' => now(),
        //         ],
        //         [
        //             'tanggal' => "20/11/23",
        //             'name' => "KOSONG",
        //             'stok_awal' => "306",
        //             'masuk' => "2",
        //             'keluar' => "0",
        //             'stok_akhir' => "306",
        //             'jumlah_stok_palet_baik' => "373",
        //             'jumlah_stok_palet_rusak' => "0",
        //             'created_at' => now(),
        //             'updated_at' => now(),
        //         ],
        //         [
        //             'tanggal' => "20/11/24",
        //             'name' => "TERPAKAI",
        //             'stok_awal' => "67",
        //             'masuk' => "0",
        //             'keluar' => "0",
        //             'stok_akhir' => "67",
        //             'jumlah_stok_palet_baik' => "373",
        //             'jumlah_stok_palet_rusak' => "0",
        //             'created_at' => now(),
        //             'updated_at' => now(),
        //         ],
        //         [
        //             'tanggal' => "20/11/24",
        //             'name' => "KOSONG",
        //             'stok_awal' => "306",
        //             'masuk' => "0",
        //             'keluar' => "0",
        //             'stok_akhir' => "306",
        //             'jumlah_stok_palet_baik' => "373",
        //             'jumlah_stok_palet_rusak' => "0",
        //             'created_at' => now(),
        //             'updated_at' => now(),
        //         ],
        //         [
        //             'tanggal' => "20/11/25",
        //             'name' => "TERPAKAI",
        //             'stok_awal' => "67",
        //             'masuk' => "0",
        //             'keluar' => "40",
        //             'stok_akhir' => "27",
        //             'jumlah_stok_palet_baik' => "373",
        //             'jumlah_stok_palet_rusak' => "0",
        //             'created_at' => now(),
        //             'updated_at' => now(),
        //         ],
        //         [
        //             'tanggal' => "20/11/25",
        //             'name' => "KOSONG",
        //             'stok_awal' => "306",
        //             'masuk' => "40",
        //             'keluar' => "0",
        //             'stok_akhir' => "346",
        //             'jumlah_stok_palet_baik' => "373",
        //             'jumlah_stok_palet_rusak' => "0",
        //             'created_at' => now(),
        //             'updated_at' => now(),
        //         ],
        //         [
        //             'tanggal' => "20/11/26",
        //             'name' => "TERPAKAI",
        //             'stok_awal' => "67",
        //             'masuk' => "0",
        //             'keluar' => "40",
        //             'stok_akhir' => "27",
        //             'jumlah_stok_palet_baik' => "372",
        //             'jumlah_stok_palet_rusak' => "0",
        //             'created_at' => now(),
        //             'updated_at' => now(),
        //         ],
        //         [
        //             'tanggal' => "20/11/26",
        //             'name' => "KOSONG",
        //             'stok_awal' => "306",
        //             'masuk' => "40",
        //             'keluar' => "0",
        //             'stok_akhir' => "346",
        //             'jumlah_stok_palet_baik' => "372",
        //             'jumlah_stok_palet_rusak' => "0",
        //             'created_at' => now(),
        //             'updated_at' => now(),
        //         ],
        //         [
        //             'tanggal' => "20/11/27",
        //             'name' => "TERPAKAI",
        //             'stok_awal' => "27",
        //             'masuk' => "0",
        //             'keluar' => "0",
        //             'stok_akhir' => "27",
        //             'jumlah_stok_palet_baik' => "372",
        //             'jumlah_stok_palet_rusak' => "0",
        //             'created_at' => now(),
        //             'updated_at' => now(),
        //         ],
        //         [
        //             'tanggal' => "20/11/27",
        //             'name' => "KOSONG",
        //             'stok_awal' => "345",
        //             'masuk' => "0",
        //             'keluar' => "0",
        //             'stok_akhir' => "345",
        //             'jumlah_stok_palet_baik' => "372",
        //             'jumlah_stok_palet_rusak' => "0",
        //             'created_at' => now(),
        //             'updated_at' => now(),
        //         ],
        //         [
        //             'tanggal' => "20/11/28",
        //             'name' => "TERPAKAI",
        //             'stok_awal' => "27",
        //             'masuk' => "0",
        //             'keluar' => "0",
        //             'stok_akhir' => "27",
        //             'jumlah_stok_palet_baik' => "352",
        //             'jumlah_stok_palet_rusak' => "0",
        //             'created_at' => now(),
        //             'updated_at' => now(),
        //         ],
        //         [
        //             'tanggal' => "20/11/28",
        //             'name' => "KOSONG",
        //             'stok_awal' => "345",
        //             'masuk' => "0",
        //             'keluar' => "20",
        //             'stok_akhir' => "325",
        //             'jumlah_stok_palet_baik' => "352",
        //             'jumlah_stok_palet_rusak' => "0",
        //             'created_at' => now(),
        //             'updated_at' => now(),
        //         ],
        //         [
        //             'tanggal' => "20/11/29",
        //             'name' => "TERPAKAI",
        //             'stok_awal' => "27",
        //             'masuk' => "11",
        //             'keluar' => "0",
        //             'stok_akhir' => "38",
        //             'jumlah_stok_palet_baik' => "348",
        //             'jumlah_stok_palet_rusak' => "0",
        //             'created_at' => now(),
        //             'updated_at' => now(),
        //         ],
        //         [
        //             'tanggal' => "20/11/29",
        //             'name' => "KOSONG",
        //             'stok_awal' => "325",
        //             'masuk' => "5",
        //             'keluar' => "20",
        //             'stok_akhir' => "310",
        //             'jumlah_stok_palet_baik' => "348",
        //             'jumlah_stok_palet_rusak' => "0",
        //             'created_at' => now(),
        //             'updated_at' => now(),
        //         ],
        //         [
        //             'tanggal' => "20/11/30",
        //             'name' => "TERPAKAI",
        //             'stok_awal' => "38",
        //             'masuk' => "9",
        //             'keluar' => "0",
        //             'stok_akhir' => "47",
        //             'jumlah_stok_palet_baik' => "358",
        //             'jumlah_stok_palet_rusak' => "0",
        //             'created_at' => now(),
        //             'updated_at' => now(),
        //         ],
        //         [
        //             'tanggal' => "20/11/30",
        //             'name' => "KOSONG",
        //             'stok_awal' => "310",
        //             'masuk' => "1",
        //             'keluar' => "0",
        //             'stok_akhir' => "311",
        //             'jumlah_stok_palet_baik' => "358",
        //             'jumlah_stok_palet_rusak' => "0",
        //             'created_at' => now(),
        //             'updated_at' => now(),
        //         ],
        //         [
        //             'tanggal' => "20/12/01",
        //             'name' => "TERPAKAI",
        //             'stok_awal' => "47",
        //             'masuk' => "0",
        //             'keluar' => "0",
        //             'stok_akhir' => "47",
        //             'jumlah_stok_palet_baik' => "358",
        //             'jumlah_stok_palet_rusak' => "0",
        //             'created_at' => now(),
        //             'updated_at' => now(),
        //         ],
        //         [
        //             'tanggal' => "20/12/01",
        //             'name' => "KOSONG",
        //             'stok_awal' => "311",
        //             'masuk' => "0",
        //             'keluar' => "0",
        //             'stok_akhir' => "311",
        //             'jumlah_stok_palet_baik' => "358",
        //             'jumlah_stok_palet_rusak' => "0",
        //             'created_at' => now(),
        //             'updated_at' => now(),
        //         ],
        //         [
        //             'tanggal' => "20/12/02",
        //             'name' => "TERPAKAI",
        //             'stok_awal' => "47",
        //             'masuk' => "0",
        //             'keluar' => "0",
        //             'stok_akhir' => "47",
        //             'jumlah_stok_palet_baik' => "358",
        //             'jumlah_stok_palet_rusak' => "0",
        //             'created_at' => now(),
        //             'updated_at' => now(),
        //         ],
        //         [
        //             'tanggal' => "20/12/02",
        //             'name' => "KOSONG",
        //             'stok_awal' => "311",
        //             'masuk' => "0",
        //             'keluar' => "0",
        //             'stok_akhir' => "311",
        //             'jumlah_stok_palet_baik' => "358",
        //             'jumlah_stok_palet_rusak' => "0",
        //             'created_at' => now(),
        //             'updated_at' => now(),
        //         ],
        //         [
        //             'tanggal' => "20/12/03",
        //             'name' => "TERPAKAI",
        //             'stok_awal' => "47",
        //             'masuk' => "0",
        //             'keluar' => "0",
        //             'stok_akhir' => "47",
        //             'jumlah_stok_palet_baik' => "358",
        //             'jumlah_stok_palet_rusak' => "0",
        //             'created_at' => now(),
        //             'updated_at' => now(),
        //         ],
        //         [
        //             'tanggal' => "20/12/03",
        //             'name' => "KOSONG",
        //             'stok_awal' => "311",
        //             'masuk' => "0",
        //             'keluar' => "0",
        //             'stok_akhir' => "311",
        //             'jumlah_stok_palet_baik' => "358",
        //             'jumlah_stok_palet_rusak' => "0",
        //             'created_at' => now(),
        //             'updated_at' => now(),
        //         ],
        //         [
        //             'tanggal' => "20/12/04",
        //             'name' => "TERPAKAI",
        //             'stok_awal' => "47",
        //             'masuk' => "0",
        //             'keluar' => "0",
        //             'stok_akhir' => "47",
        //             'jumlah_stok_palet_baik' => "358",
        //             'jumlah_stok_palet_rusak' => "0",
        //             'created_at' => now(),
        //             'updated_at' => now(),
        //         ],
        //         [
        //             'tanggal' => "20/12/04",
        //             'name' => "KOSONG",
        //             'stok_awal' => "311",
        //             'masuk' => "0",
        //             'keluar' => "0",
        //             'stok_akhir' => "311",
        //             'jumlah_stok_palet_baik' => "358",
        //             'jumlah_stok_palet_rusak' => "0",
        //             'created_at' => now(),
        //             'updated_at' => now(),
        //         ],
        //         [
        //             'tanggal' => "20/12/05",
        //             'name' => "TERPAKAI",
        //             'stok_awal' => "47",
        //             'masuk' => "0",
        //             'keluar' => "0",
        //             'stok_akhir' => "47",
        //             'jumlah_stok_palet_baik' => "358",
        //             'jumlah_stok_palet_rusak' => "0",
        //             'created_at' => now(),
        //             'updated_at' => now(),
        //         ],
        //         [
        //             'tanggal' => "20/12/05",
        //             'name' => "KOSONG",
        //             'stok_awal' => "311",
        //             'masuk' => "0",
        //             'keluar' => "0",
        //             'stok_akhir' => "311",
        //             'jumlah_stok_palet_baik' => "358",
        //             'jumlah_stok_palet_rusak' => "0",
        //             'created_at' => now(),
        //             'updated_at' => now(),
        //         ],
        //         [
        //             'tanggal' => "20/12/06",
        //             'name' => "TERPAKAI",
        //             'stok_awal' => "47",
        //             'masuk' => "0",
        //             'keluar' => "0",
        //             'stok_akhir' => "47",
        //             'jumlah_stok_palet_baik' => "358",
        //             'jumlah_stok_palet_rusak' => "0",
        //             'created_at' => now(),
        //             'updated_at' => now(),
        //         ],
        //         [
        //             'tanggal' => "20/12/06",
        //             'name' => "KOSONG",
        //             'stok_awal' => "311",
        //             'masuk' => "0",
        //             'keluar' => "0",
        //             'stok_akhir' => "311",
        //             'jumlah_stok_palet_baik' => "358",
        //             'jumlah_stok_palet_rusak' => "0",
        //             'created_at' => now(),
        //             'updated_at' => now(),
        //         ],
        //         [
        //             'tanggal' => "20/12/07",
        //             'name' => "TERPAKAI",
        //             'stok_awal' => "47",
        //             'masuk' => "0",
        //             'keluar' => "46",
        //             'stok_akhir' => "1",
        //             'jumlah_stok_palet_baik' => "305",
        //             'jumlah_stok_palet_rusak' => "0",
        //             'created_at' => now(),
        //             'updated_at' => now(),
        //         ],
        //         [
        //             'tanggal' => "20/12/07",
        //             'name' => "KOSONG",
        //             'stok_awal' => "311",
        //             'masuk' => "0",
        //             'keluar' => "7",
        //             'stok_akhir' => "304",
        //             'jumlah_stok_palet_baik' => "305",
        //             'jumlah_stok_palet_rusak' => "0",
        //             'created_at' => now(),
        //             'updated_at' => now(),
        //         ],
        //         [
        //             'tanggal' => "20/12/08",
        //             'name' => "TERPAKAI",
        //             'stok_awal' => "1",
        //             'masuk' => "0",
        //             'keluar' => "0",
        //             'stok_akhir' => "1",
        //             'jumlah_stok_palet_baik' => "305",
        //             'jumlah_stok_palet_rusak' => "0",
        //             'created_at' => now(),
        //             'updated_at' => now(),
        //         ],
        //         [
        //             'tanggal' => "20/12/08",
        //             'name' => "KOSONG",
        //             'stok_awal' => "304",
        //             'masuk' => "0",
        //             'keluar' => "0",
        //             'stok_akhir' => "304",
        //             'jumlah_stok_palet_baik' => "305",
        //             'jumlah_stok_palet_rusak' => "0",
        //             'created_at' => now(),
        //             'updated_at' => now(),
        //         ],
        //         [
        //             'tanggal' => "20/12/09",
        //             'name' => "TERPAKAI",
        //             'stok_awal' => "1",
        //             'masuk' => "0",
        //             'keluar' => "0",
        //             'stok_akhir' => "1",
        //             'jumlah_stok_palet_baik' => "305",
        //             'jumlah_stok_palet_rusak' => "0",
        //             'created_at' => now(),
        //             'updated_at' => now(),
        //         ],
        //         [
        //             'tanggal' => "20/12/09",
        //             'name' => "KOSONG",
        //             'stok_awal' => "304",
        //             'masuk' => "0",
        //             'keluar' => "0",
        //             'stok_akhir' => "304",
        //             'jumlah_stok_palet_baik' => "305",
        //             'jumlah_stok_palet_rusak' => "0",
        //             'created_at' => now(),
        //             'updated_at' => now(),
        //         ],
        //         [
        //             'tanggal' => "20/12/10",
        //             'name' => "TERPAKAI",
        //             'stok_awal' => "1",
        //             'masuk' => "0",
        //             'keluar' => "0",
        //             'stok_akhir' => "1",
        //             'jumlah_stok_palet_baik' => "380",
        //             'jumlah_stok_palet_rusak' => "0",
        //             'created_at' => now(),
        //             'updated_at' => now(),
        //         ],
        //         [
        //             'tanggal' => "20/12/10",
        //             'name' => "KOSONG",
        //             'stok_awal' => "304",
        //             'masuk' => "0",
        //             'keluar' => "25",
        //             'stok_akhir' => "279",
        //             'jumlah_stok_palet_baik' => "380",
        //             'jumlah_stok_palet_rusak' => "0",
        //             'created_at' => now(),
        //             'updated_at' => now(),
        //         ],
        //         [
        //             'tanggal' => "20/12/11",
        //             'name' => "TERPAKAI",
        //             'stok_awal' => "1",
        //             'masuk' => "14",
        //             'keluar' => "0",
        //             'stok_akhir' => "15",
        //             'jumlah_stok_palet_baik' => "294",
        //             'jumlah_stok_palet_rusak' => "0",
        //             'created_at' => now(),
        //             'updated_at' => now(),
        //         ],
        //         [
        //             'tanggal' => "20/12/11",
        //             'name' => "KOSONG",
        //             'stok_awal' => "279",
        //             'masuk' => "0",
        //             'keluar' => "0",
        //             'stok_akhir' => "279",
        //             'jumlah_stok_palet_baik' => "294",
        //             'jumlah_stok_palet_rusak' => "0",
        //             'created_at' => now(),
        //             'updated_at' => now(),
        //         ],
        //         [
        //             'tanggal' => "20/12/12",
        //             'name' => "TERPAKAI",
        //             'stok_awal' => "15",
        //             'masuk' => "0",
        //             'keluar' => "0",
        //             'stok_akhir' => "15",
        //             'jumlah_stok_palet_baik' => "294",
        //             'jumlah_stok_palet_rusak' => "0",
        //             'created_at' => now(),
        //             'updated_at' => now(),
        //         ],
        //         [
        //             'tanggal' => "20/12/12",
        //             'name' => "KOSONG",
        //             'stok_awal' => "279",
        //             'masuk' => "0",
        //             'keluar' => "0",
        //             'stok_akhir' => "279",
        //             'jumlah_stok_palet_baik' => "294",
        //             'jumlah_stok_palet_rusak' => "0",
        //             'created_at' => now(),
        //             'updated_at' => now(),
        //         ],
        //         [
        //             'tanggal' => "20/12/13",
        //             'name' => "TERPAKAI",
        //             'stok_awal' => "15",
        //             'masuk' => "0",
        //             'keluar' => "0",
        //             'stok_akhir' => "15",
        //             'jumlah_stok_palet_baik' => "294",
        //             'jumlah_stok_palet_rusak' => "0",
        //             'created_at' => now(),
        //             'updated_at' => now(),
        //         ],
        //         [
        //             'tanggal' => "20/12/13",
        //             'name' => "KOSONG",
        //             'stok_awal' => "279",
        //             'masuk' => "0",
        //             'keluar' => "0",
        //             'stok_akhir' => "279",
        //             'jumlah_stok_palet_baik' => "294",
        //             'jumlah_stok_palet_rusak' => "0",
        //             'created_at' => now(),
        //             'updated_at' => now(),
        //         ],
        //         [
        //             'tanggal' => "20/12/14",
        //             'name' => "TERPAKAI",
        //             'stok_awal' => "15",
        //             'masuk' => "0",
        //             'keluar' => "0",
        //             'stok_akhir' => "15",
        //             'jumlah_stok_palet_baik' => "294",
        //             'jumlah_stok_palet_rusak' => "0",
        //             'created_at' => now(),
        //             'updated_at' => now(),
        //         ],
        //         [
        //             'tanggal' => "20/12/14",
        //             'name' => "KOSONG",
        //             'stok_awal' => "279",
        //             'masuk' => "0",
        //             'keluar' => "0",
        //             'stok_akhir' => "279",
        //             'jumlah_stok_palet_baik' => "294",
        //             'jumlah_stok_palet_rusak' => "0",
        //             'created_at' => now(),
        //             'updated_at' => now(),
        //         ],
        //         [
        //             'tanggal' => "20/12/15",
        //             'name' => "TERPAKAI",
        //             'stok_awal' => "15",
        //             'masuk' => "0",
        //             'keluar' => "0",
        //             'stok_akhir' => "15",
        //             'jumlah_stok_palet_baik' => "294",
        //             'jumlah_stok_palet_rusak' => "0",
        //             'created_at' => now(),
        //             'updated_at' => now(),
        //         ],
        //         [
        //             'tanggal' => "20/12/15",
        //             'name' => "KOSONG",
        //             'stok_awal' => "279",
        //             'masuk' => "0",
        //             'keluar' => "0",
        //             'stok_akhir' => "279",
        //             'jumlah_stok_palet_baik' => "294",
        //             'jumlah_stok_palet_rusak' => "0",
        //             'created_at' => now(),
        //             'updated_at' => now(),
        //         ],
        //         [
        //             'tanggal' => "20/12/16",
        //             'name' => "TERPAKAI",
        //             'stok_awal' => "15",
        //             'masuk' => "0",
        //             'keluar' => "0",
        //             'stok_akhir' => "15",
        //             'jumlah_stok_palet_baik' => "294",
        //             'jumlah_stok_palet_rusak' => "0",
        //             'created_at' => now(),
        //             'updated_at' => now(),
        //         ],
        //         [
        //             'tanggal' => "20/12/16",
        //             'name' => "KOSONG",
        //             'stok_awal' => "279",
        //             'masuk' => "0",
        //             'keluar' => "0",
        //             'stok_akhir' => "279",
        //             'jumlah_stok_palet_baik' => "294",
        //             'jumlah_stok_palet_rusak' => "0",
        //             'created_at' => now(),
        //             'updated_at' => now(),
        //         ],
        //         [
        //             'tanggal' => "20/12/17",
        //             'name' => "TERPAKAI",
        //             'stok_awal' => "15",
        //             'masuk' => "5",
        //             'keluar' => "0",
        //             'stok_akhir' => "20",
        //             'jumlah_stok_palet_baik' => "301",
        //             'jumlah_stok_palet_rusak' => "0",
        //             'created_at' => now(),
        //             'updated_at' => now(),
        //         ],
        //         [
        //             'tanggal' => "20/12/17",
        //             'name' => "KOSONG",
        //             'stok_awal' => "279",
        //             'masuk' => "2",
        //             'keluar' => "0",
        //             'stok_akhir' => "281",
        //             'jumlah_stok_palet_baik' => "301",
        //             'jumlah_stok_palet_rusak' => "0",
        //             'created_at' => now(),
        //             'updated_at' => now(),
        //         ],
        //         [
        //             'tanggal' => "20/12/18",
        //             'name' => "TERPAKAI",
        //             'stok_awal' => "20",
        //             'masuk' => "0",
        //             'keluar' => "11",
        //             'stok_akhir' => "9",
        //             'jumlah_stok_palet_baik' => "301",
        //             'jumlah_stok_palet_rusak' => "0",
        //             'created_at' => now(),
        //             'updated_at' => now(),
        //         ],
        //         [
        //             'tanggal' => "20/12/18",
        //             'name' => "KOSONG",
        //             'stok_awal' => "281",
        //             'masuk' => "11",
        //             'keluar' => "0",
        //             'stok_akhir' => "292",
        //             'jumlah_stok_palet_baik' => "301",
        //             'jumlah_stok_palet_rusak' => "0",
        //             'created_at' => now(),
        //             'updated_at' => now(),
        //         ],
        //         [
        //             'tanggal' => "20/12/19",
        //             'name' => "TERPAKAI",
        //             'stok_awal' => "9",
        //             'masuk' => "0",
        //             'keluar' => "0",
        //             'stok_akhir' => "9",
        //             'jumlah_stok_palet_baik' => "301",
        //             'jumlah_stok_palet_rusak' => "0",
        //             'created_at' => now(),
        //             'updated_at' => now(),
        //         ],
        //         [
        //             'tanggal' => "20/12/19",
        //             'name' => "KOSONG",
        //             'stok_awal' => "292",
        //             'masuk' => "0",
        //             'keluar' => "0",
        //             'stok_akhir' => "292",
        //             'jumlah_stok_palet_baik' => "301",
        //             'jumlah_stok_palet_rusak' => "0",
        //             'created_at' => now(),
        //             'updated_at' => now(),
        //         ],
        //         [
        //             'tanggal' => "20/12/20",
        //             'name' => "TERPAKAI",
        //             'stok_awal' => "9",
        //             'masuk' => "0",
        //             'keluar' => "0",
        //             'stok_akhir' => "9",
        //             'jumlah_stok_palet_baik' => "301",
        //             'jumlah_stok_palet_rusak' => "0",
        //             'created_at' => now(),
        //             'updated_at' => now(),
        //         ],
        //         [
        //             'tanggal' => "20/12/20",
        //             'name' => "KOSONG",
        //             'stok_awal' => "292",
        //             'masuk' => "0",
        //             'keluar' => "0",
        //             'stok_akhir' => "292",
        //             'jumlah_stok_palet_baik' => "301",
        //             'jumlah_stok_palet_rusak' => "0",
        //             'created_at' => now(),
        //             'updated_at' => now(),
        //         ],
        //         [
        //             'tanggal' => "20/12/21",
        //             'name' => "TERPAKAI",
        //             'stok_awal' => "9",
        //             'masuk' => "0",
        //             'keluar' => "0",
        //             'stok_akhir' => "9",
        //             'jumlah_stok_palet_baik' => "301",
        //             'jumlah_stok_palet_rusak' => "0",
        //             'created_at' => now(),
        //             'updated_at' => now(),
        //         ],
        //         [
        //             'tanggal' => "20/12/21",
        //             'name' => "KOSONG",
        //             'stok_awal' => "292",
        //             'masuk' => "0",
        //             'keluar' => "0",
        //             'stok_akhir' => "292",
        //             'jumlah_stok_palet_baik' => "301",
        //             'jumlah_stok_palet_rusak' => "0",
        //             'created_at' => now(),
        //             'updated_at' => now(),
        //         ],
        //         [
        //             'tanggal' => "20/12/22",
        //             'name' => "TERPAKAI",
        //             'stok_awal' => "9",
        //             'masuk' => "0",
        //             'keluar' => "0",
        //             'stok_akhir' => "9",
        //             'jumlah_stok_palet_baik' => "301",
        //             'jumlah_stok_palet_rusak' => "0",
        //             'created_at' => now(),
        //             'updated_at' => now(),
        //         ],
        //         [
        //             'tanggal' => "20/12/22",
        //             'name' => "KOSONG",
        //             'stok_awal' => "292",
        //             'masuk' => "0",
        //             'keluar' => "0",
        //             'stok_akhir' => "292",
        //             'jumlah_stok_palet_baik' => "301",
        //             'jumlah_stok_palet_rusak' => "0",
        //             'created_at' => now(),
        //             'updated_at' => now(),
        //         ],
        //         [
        //             'tanggal' => "20/12/23",
        //             'name' => "TERPAKAI",
        //             'stok_awal' => "9",
        //             'masuk' => "0",
        //             'keluar' => "0",
        //             'stok_akhir' => "9",
        //             'jumlah_stok_palet_baik' => "301",
        //             'jumlah_stok_palet_rusak' => "0",
        //             'created_at' => now(),
        //             'updated_at' => now(),
        //         ],
        //         [
        //             'tanggal' => "20/12/23",
        //             'name' => "KOSONG",
        //             'stok_awal' => "292",
        //             'masuk' => "0",
        //             'keluar' => "0",
        //             'stok_akhir' => "292",
        //             'jumlah_stok_palet_baik' => "301",
        //             'jumlah_stok_palet_rusak' => "0",
        //             'created_at' => now(),
        //             'updated_at' => now(),
        //         ],
        //         [
        //             'tanggal' => "20/12/24",
        //             'name' => "TERPAKAI",
        //             'stok_awal' => "9",
        //             'masuk' => "11",
        //             'keluar' => "0",
        //             'stok_akhir' => "20",
        //             'jumlah_stok_palet_baik' => "294",
        //             'jumlah_stok_palet_rusak' => "0",
        //             'created_at' => now(),
        //             'updated_at' => now(),
        //         ],
        //         [
        //             'tanggal' => "20/12/24",
        //             'name' => "KOSONG",
        //             'stok_awal' => "292",
        //             'masuk' => "2",
        //             'keluar' => "20",
        //             'stok_akhir' => "274",
        //             'jumlah_stok_palet_baik' => "294",
        //             'jumlah_stok_palet_rusak' => "0",
        //             'created_at' => now(),
        //             'updated_at' => now(),
        //         ],
        //         [
        //             'tanggal' => "20/12/25",
        //             'name' => "TERPAKAI",
        //             'stok_awal' => "20",
        //             'masuk' => "0",
        //             'keluar' => "0",
        //             'stok_akhir' => "20",
        //             'jumlah_stok_palet_baik' => "294",
        //             'jumlah_stok_palet_rusak' => "0",
        //             'created_at' => now(),
        //             'updated_at' => now(),
        //         ],
        //         [
        //             'tanggal' => "20/12/25",
        //             'name' => "KOSONG",
        //             'stok_awal' => "274",
        //             'masuk' => "0",
        //             'keluar' => "0",
        //             'stok_akhir' => "274",
        //             'jumlah_stok_palet_baik' => "294",
        //             'jumlah_stok_palet_rusak' => "0",
        //             'created_at' => now(),
        //             'updated_at' => now(),
        //         ],
        //         [
        //             'tanggal' => "20/12/26",
        //             'name' => "TERPAKAI",
        //             'stok_awal' => "20",
        //             'masuk' => "0",
        //             'keluar' => "0",
        //             'stok_akhir' => "20",
        //             'jumlah_stok_palet_baik' => "294",
        //             'jumlah_stok_palet_rusak' => "0",
        //             'created_at' => now(),
        //             'updated_at' => now(),
        //         ],
        //         [
        //             'tanggal' => "20/12/26",
        //             'name' => "KOSONG",
        //             'stok_awal' => "274",
        //             'masuk' => "0",
        //             'keluar' => "0",
        //             'stok_akhir' => "274",
        //             'jumlah_stok_palet_baik' => "294",
        //             'jumlah_stok_palet_rusak' => "0",
        //             'created_at' => now(),
        //             'updated_at' => now(),
        //         ],
        //         [
        //             'tanggal' => "20/12/27",
        //             'name' => "TERPAKAI",
        //             'stok_awal' => "20",
        //             'masuk' => "0",
        //             'keluar' => "0",
        //             'stok_akhir' => "20",
        //             'jumlah_stok_palet_baik' => "254",
        //             'jumlah_stok_palet_rusak' => "0",
        //             'created_at' => now(),
        //             'updated_at' => now(),
        //         ],
        //         [
        //             'tanggal' => "20/12/27",
        //             'name' => "KOSONG",
        //             'stok_awal' => "274",
        //             'masuk' => "0",
        //             'keluar' => "40",
        //             'stok_akhir' => "234",
        //             'jumlah_stok_palet_baik' => "254",
        //             'jumlah_stok_palet_rusak' => "0",
        //             'created_at' => now(),
        //             'updated_at' => now(),
        //         ],
        //         [
        //             'tanggal' => "20/12/28",
        //             'name' => "TERPAKAI",
        //             'stok_awal' => "20",
        //             'masuk' => "12",
        //             'keluar' => "0",
        //             'stok_akhir' => "32",
        //             'jumlah_stok_palet_baik' => "249",
        //             'jumlah_stok_palet_rusak' => "0",
        //             'created_at' => now(),
        //             'updated_at' => now(),
        //         ],
        //         [
        //             'tanggal' => "20/12/28",
        //             'name' => "KOSONG",
        //             'stok_awal' => "234",
        //             'masuk' => "3",
        //             'keluar' => "20",
        //             'stok_akhir' => "217",
        //             'jumlah_stok_palet_baik' => "249",
        //             'jumlah_stok_palet_rusak' => "0",
        //             'created_at' => now(),
        //             'updated_at' => now(),
        //         ],
        //         [
        //             'tanggal' => "20/12/29",
        //             'name' => "TERPAKAI",
        //             'stok_awal' => "32",
        //             'masuk' => "11",
        //             'keluar' => "0",
        //             'stok_akhir' => "43",
        //             'jumlah_stok_palet_baik' => "270",
        //             'jumlah_stok_palet_rusak' => "0",
        //             'created_at' => now(),
        //             'updated_at' => now(),
        //         ],
        //         [
        //             'tanggal' => "20/12/29",
        //             'name' => "KOSONG",
        //             'stok_awal' => "217",
        //             'masuk' => "10",
        //             'keluar' => "0",
        //             'stok_akhir' => "227",
        //             'jumlah_stok_palet_baik' => "270",
        //             'jumlah_stok_palet_rusak' => "0",
        //             'created_at' => now(),
        //             'updated_at' => now(),
        //         ],
        //         [
        //             'tanggal' => "20/12/30",
        //             'name' => "TERPAKAI",
        //             'stok_awal' => "43",
        //             'masuk' => "38",
        //             'keluar' => "0",
        //             'stok_akhir' => "81",
        //             'jumlah_stok_palet_baik' => "310",
        //             'jumlah_stok_palet_rusak' => "0",
        //             'created_at' => now(),
        //             'updated_at' => now(),
        //         ],
        //         [
        //             'tanggal' => "20/12/30",
        //             'name' => "KOSONG",
        //             'stok_awal' => "227",
        //             'masuk' => "2",
        //             'keluar' => "0",
        //             'stok_akhir' => "229",
        //             'jumlah_stok_palet_baik' => "310",
        //             'jumlah_stok_palet_rusak' => "0",
        //             'created_at' => now(),
        //             'updated_at' => now(),
        //         ],
        //         [
        //             'tanggal' => "20/12/31",
        //             'name' => "TERPAKAI",
        //             'stok_awal' => "81",
        //             'masuk' => "10",
        //             'keluar' => "89",
        //             'stok_akhir' => "2",
        //             'jumlah_stok_palet_baik' => "200",
        //             'jumlah_stok_palet_rusak' => "0",
        //             'created_at' => now(),
        //             'updated_at' => now(),
        //         ],
        //         [
        //             'tanggal' => "20/12/31",
        //             'name' => "KOSONG",
        //             'stok_awal' => "229",
        //             'masuk' => "0",
        //             'keluar' => "31",
        //             'stok_akhir' => "198",
        //             'jumlah_stok_palet_baik' => "200",
        //             'jumlah_stok_palet_rusak' => "0",
        //             'created_at' => now(),
        //             'updated_at' => now(),
        //         ],
        //         [
        //             'tanggal' => "21/01/01",
        //             'name' => "TERPAKAI",
        //             'stok_awal' => "2",
        //             'masuk' => "13",
        //             'keluar' => "0",
        //             'stok_akhir' => "15",
        //             'jumlah_stok_palet_baik' => "214",
        //             'jumlah_stok_palet_rusak' => "0",
        //             'created_at' => now(),
        //             'updated_at' => now(),
        //         ],
        //         [
        //             'tanggal' => "21/01/01",
        //             'name' => "KOSONG",
        //             'stok_awal' => "198",
        //             'masuk' => "1",
        //             'keluar' => "0",
        //             'stok_akhir' => "199",
        //             'jumlah_stok_palet_baik' => "214",
        //             'jumlah_stok_palet_rusak' => "0",
        //             'created_at' => now(),
        //             'updated_at' => now(),
        //         ],
        //         [
        //             'tanggal' => "21/01/02",
        //             'name' => "TERPAKAI",
        //             'stok_awal' => "15",
        //             'masuk' => "0",
        //             'keluar' => "0",
        //             'stok_akhir' => "15",
        //             'jumlah_stok_palet_baik' => "171",
        //             'jumlah_stok_palet_rusak' => "0",
        //             'created_at' => now(),
        //             'updated_at' => now(),
        //         ],
        //         [
        //             'tanggal' => "21/01/02",
        //             'name' => "KOSONG",
        //             'stok_awal' => "199",
        //             'masuk' => "0",
        //             'keluar' => "43",
        //             'stok_akhir' => "156",
        //             'jumlah_stok_palet_baik' => "171",
        //             'jumlah_stok_palet_rusak' => "0",
        //             'created_at' => now(),
        //             'updated_at' => now(),
        //         ],
            ]
        );

        // Data::factory()->count(10)->create();

    }
}
